import "./ActivityCalender.scss"

const ActivityCalender = () => {
  return (
    <section className="activity-calender">
      <h2>Aktiviteter vecka 37</h2>

      <table>
        <thead>
          <tr>
            <th>Tid</th>
            <th>Måndag</th>
            <th>Tisdag</th>
            <th>Onsdag</th>
            <th>Torsdag</th>
            <th>Fredag</th>
            <th>Lördag</th>
            <th>Söndag</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>07:00</td>
            <td>Bordtennis</td>
            <td>Bordtennis</td>
            <td>Bordtennis</td>
            <td>Bordtennis</td>
            <td>Bordtennis</td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>08:00</td>
            <td></td>
            <td></td>
            <td>Yoga</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>09:00</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>10:00</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Prommenad</td>
            <td>Prommenad</td>
          </tr>
          <tr>
            <td>11:00</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>12:00</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>13:00</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>14:00</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>15:00</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>16:00</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>17:00</td>
            <td></td>
            <td></td>
            <td></td>
            <td>DiscGolf</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>18:00</td>
            <td></td>
            <td></td>
            <td></td>
            <td>Bågskytte</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>19:00</td>
            <td></td>
            <td></td>
            <td>Minigolf</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>20:00</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td>21:00</td>
            <td>Bridge</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </section>
  )
}
export default ActivityCalender
